// src/app/core/constants/address-data.ts

export const ADDRESS_DATA = [
  {
    id: 1,
    name: 'Brazil',
    code: 'BR',
    states: [
      { id: 1, name: 'Acre' },
      { id: 2, name: 'Alagoas' },
      { id: 3, name: 'Amapá' },
      { id: 4, name: 'Amazonas' },
      { id: 5, name: 'Bahia' },
      { id: 6, name: 'Ceará' },
      { id: 7, name: 'Distrito Federal' },
      { id: 8, name: 'Espírito Santo' },
      { id: 9, name: 'Goiás' },
      { id: 10, name: 'Maranhão' },
      { id: 11, name: 'Mato Grosso do Sul' },
      { id: 12, name: 'Mato Grosso' },
      { id: 13, name: 'Minas Gerais' },
      { id: 14, name: 'Paraná' },
      { id: 15, name: 'Paraíba' },
      { id: 16, name: 'Pará' },
      { id: 17, name: 'Pernambuco' },
      { id: 18, name: 'Piaui' },
      { id: 19, name: 'Rio de Janeiro' },
      { id: 20, name: 'Rio Grande do Norte' },
      { id: 21, name: 'Rio Grande do Sul' },
      { id: 22, name: 'Rondônia' },
      { id: 23, name: 'Roraima' },
      { id: 24, name: 'Santa Catarina' },
      { id: 25, name: 'Sergipe' },
      { id: 26, name: 'São Paulo' },
      { id: 27, name: 'Tocantins' },
    ],
  },
  {
    id: 2,
    name: 'Canada',
    code: 'CA',
    states: [
      { id: 28, name: 'Alberta' },
      { id: 29, name: 'British Columbia' },
      { id: 30, name: 'Manitoba' },
      { id: 31, name: 'New Brunswick' },
      { id: 32, name: 'Newfoundland and Labrador' },
      { id: 33, name: 'Northwest Territories' },
      { id: 34, name: 'Nova Scotia' },
      { id: 35, name: 'Nunavut' },
      { id: 36, name: 'Ontario' },
      { id: 37, name: 'Prince Edward Island' },
      { id: 38, name: 'Quebec' },
      { id: 39, name: 'Saskatchewan' },
      { id: 40, name: 'Yukon' },
    ],
  },
  {
    id: 3,
    name: 'Germany',
    code: 'DE',
    states: [
      { id: 41, name: 'Baden-Württemberg' },
      { id: 42, name: 'Bavaria' },
      { id: 43, name: 'Berlin' },
      { id: 44, name: 'Brandenburg' },
      { id: 45, name: 'Bremen' },
      { id: 46, name: 'Hamburg' },
      { id: 47, name: 'Hesse' },
      { id: 48, name: 'Lower Saxony' },
      { id: 49, name: 'Mecklenburg-Vorpommern' },
      { id: 50, name: 'North Rhine-Westphalia' },
      { id: 51, name: 'Rhineland-Palatinate' },
      { id: 52, name: 'Saarland' },
      { id: 53, name: 'Saxony' },
      { id: 54, name: 'Saxony-Anhalt' },
      { id: 55, name: 'Schleswig-Holstein' },
      { id: 56, name: 'Thuringia' },
    ],
  },
  {
    id: 4,
    name: 'India',
    code: 'IN',
    states: [
      { id: 57, name: 'Andhra Pradesh' },
      { id: 58, name: 'Arunachal Pradesh' },
      { id: 59, name: 'Assam' },
      { id: 60, name: 'Bihar' },
      { id: 61, name: 'Chhattisgarh' },
      { id: 62, name: 'Goa' },
      { id: 63, name: 'Gujarat' },
      { id: 64, name: 'Haryana' },
      { id: 65, name: 'Himachal Pradesh' },
      { id: 66, name: 'Jammu & Kashmir' },
      { id: 67, name: 'Jharkhand' },
      { id: 68, name: 'Karnataka' },
      { id: 69, name: 'Kerala' },
      { id: 70, name: 'Madhya Pradesh' },
      { id: 71, name: 'Maharashtra' },
      { id: 72, name: 'Manipur' },
      { id: 73, name: 'Meghalaya' },
      { id: 74, name: 'Mizoram' },
      { id: 75, name: 'Nagaland' },
      { id: 76, name: 'Odisha' },
      { id: 77, name: 'Punjab' },
      { id: 78, name: 'Rajasthan' },
      { id: 79, name: 'Sikkim' },
      { id: 80, name: 'Tamil Nadu' },
      { id: 81, name: 'Telangana' },
      { id: 82, name: 'Tripura' },
      { id: 83, name: 'Uttar Pradesh' },
      { id: 84, name: 'Uttarakhand' },
      { id: 85, name: 'West Bengal' },
      { id: 86, name: 'Andaman and Nicobar Islands' },
      { id: 87, name: 'Chandigarh' },
      { id: 88, name: 'Dadra and Nagar Haveli' },
      { id: 89, name: 'Daman & Diu' },
      { id: 90, name: 'Lakshadweep' },
      { id: 91, name: 'Puducherry' },
      { id: 92, name: 'The Government of NCT of Delhi' },
    ],
  },
  {
    id: 5,
    name: 'Turkey',
    code: 'TR',
    states: [
      { id: 144, name: 'Adıyaman' },
      { id: 145, name: 'Afyonkarahisar' },
      { id: 146, name: 'Ağrı' },
      { id: 147, name: 'Aksaray' },
      { id: 148, name: 'Amasya' },
      { id: 149, name: 'Ankara' },
      { id: 150, name: 'Antalya' },
      { id: 151, name: 'Ardahan' },
      { id: 152, name: 'Artvin' },
      { id: 153, name: 'Aydın' },
      { id: 154, name: 'Balıkesir' },
      { id: 155, name: 'Bartın' },
      { id: 156, name: 'Batman' },
      { id: 157, name: 'Bayburt' },
      { id: 158, name: 'Bilecik' },
      { id: 159, name: 'Bingöl' },
      { id: 160, name: 'Bitlis' },
      { id: 161, name: 'Bolu' },
      { id: 162, name: 'Burdur' },
      { id: 163, name: 'Bursa' },
      { id: 164, name: 'Çanakkale' },
      { id: 165, name: 'Çankırı' },
      { id: 166, name: 'Çorum' },
      { id: 167, name: 'Denizli' },
      { id: 168, name: 'Diyarbakır' },
      { id: 169, name: 'Düzce' },
      { id: 170, name: 'Edirne' },
      { id: 171, name: 'Elazığ' },
      { id: 172, name: 'Erzincan' },
      { id: 173, name: 'Erzurum' },
      { id: 174, name: 'Eskişehir' },
      { id: 175, name: 'Gaziantep' },
      { id: 176, name: 'Giresun' },
      { id: 177, name: 'Gümüşhane' },
      { id: 178, name: 'Hakkâri' },
      { id: 179, name: 'Hatay' },
      { id: 180, name: 'Iğdır' },
      { id: 181, name: 'Isparta' },
      { id: 182, name: 'İstanbul' },
      { id: 183, name: 'İzmir' },
      { id: 184, name: 'Kahramanmaraş' },
      { id: 185, name: 'Karabük' },
      { id: 186, name: 'Karaman' },
      { id: 187, name: 'Kars' },
      { id: 188, name: 'Kastamonu' },
      { id: 189, name: 'Kayseri' },
      { id: 190, name: 'Kırıkkale' },
      { id: 191, name: 'Kırklareli' },
      { id: 192, name: 'Kırşehir' },
      { id: 193, name: 'Kilis' },
      { id: 194, name: 'Kocaeli' },
      { id: 195, name: 'Konya' },
      { id: 196, name: 'Kütahya' },
      { id: 197, name: 'Malatya' },
      { id: 198, name: 'Manisa' },
      { id: 199, name: 'Mardin' },
      { id: 200, name: 'Mersin' },
      { id: 201, name: 'Muğla' },
      { id: 202, name: 'Muş' },
      { id: 203, name: 'Nevşehir' },
      { id: 204, name: 'Niğde' },
      { id: 205, name: 'Ordu' },
      { id: 206, name: 'Osmaniye' },
      { id: 207, name: 'Rize' },
      { id: 208, name: 'Sakarya' },
      { id: 209, name: 'Samsun' },
      { id: 210, name: 'Siirt' },
      { id: 211, name: 'Sinop' },
      { id: 212, name: 'Sivas' },
      { id: 213, name: 'Şanlıurfa' },
      { id: 214, name: 'Şırnak' },
      { id: 215, name: 'Tekirdağ' },
      { id: 216, name: 'Tokat' },
      { id: 217, name: 'Trabzon' },
      { id: 218, name: 'Tunceli' },
      { id: 219, name: 'Uşak' },
      { id: 220, name: 'Van' },
      { id: 221, name: 'Yalova' },
      { id: 222, name: 'Yozgat' },
      { id: 223, name: 'Zonguldak' },
    ],
  },
  {
    id: 6,
    name: 'United States',
    code: 'US',
    states: [
      { id: 93, name: 'Alabama' },
      { id: 94, name: 'Alaska' },
      { id: 95, name: 'Arizona' },
      { id: 96, name: 'Arkansas' },
      { id: 97, name: 'California' },
      { id: 98, name: 'Colorado' },
      { id: 99, name: 'Connecticut' },
      { id: 100, name: 'Delaware' },
      { id: 101, name: 'District Of Columbia' },
      { id: 102, name: 'Florida' },
      { id: 103, name: 'Georgia' },
      { id: 104, name: 'Hawaii' },
      { id: 105, name: 'Idaho' },
      { id: 106, name: 'Illinois' },
      { id: 107, name: 'Indiana' },
      { id: 108, name: 'Iowa' },
      { id: 109, name: 'Kansas' },
      { id: 110, name: 'Kentucky' },
      { id: 111, name: 'Louisiana' },
      { id: 112, name: 'Maine' },
      { id: 113, name: 'Maryland' },
      { id: 114, name: 'Massachusetts' },
      { id: 115, name: 'Michigan' },
      { id: 116, name: 'Minnesota' },
      { id: 117, name: 'Mississippi' },
      { id: 118, name: 'Missouri' },
      { id: 119, name: 'Montana' },
      { id: 120, name: 'Nebraska' },
      { id: 121, name: 'Nevada' },
      { id: 122, name: 'New Hampshire' },
      { id: 123, name: 'New Jersey' },
      { id: 124, name: 'New Mexico' },
      { id: 125, name: 'New York' },
      { id: 126, name: 'North Carolina' },
      { id: 127, name: 'North Dakota' },
      { id: 128, name: 'Ohio' },
      { id: 129, name: 'Oklahoma' },
      { id: 130, name: 'Oregon' },
      { id: 131, name: 'Pennsylvania' },
      { id: 132, name: 'Rhode Island' },
      { id: 133, name: 'South Carolina' },
      { id: 134, name: 'South Dakota' },
      { id: 135, name: 'Tennessee' },
      { id: 136, name: 'Texas' },
      { id: 137, name: 'Utah' },
      { id: 138, name: 'Vermont' },
      { id: 139, name: 'Virginia' },
      { id: 140, name: 'Washington' },
      { id: 141, name: 'West Virginia' },
      { id: 142, name: 'Wisconsin' },
      { id: 143, name: 'Wyoming' },
    ],
  },
];
